name: attendance_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.15.6
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  intl: ^0.18.0
  image_picker: ^0.8.4+2  # Add this line for image picker dependency
  firebase_storage: ^11.0.0  # Updated version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Judson
      fonts:
        - asset: assets/fonts/JudsonRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
